
- oso_service:
    service_name: nginx
    project_name: playbook-etherpad
    labels:
      app: playbook-etherpad
      service: nginx
    ports:
    - name: port-80
      port: 80
      targetPort: 80
    selector:
      app: playbook-etherpad
      service: nginx
  register: output

- debug: var=output
  when: playbook_debug

- oso_service:
    service_name: mariadb
    project_name: playbook-etherpad
    labels:
      app: playbook-etherpad
      service: mariadb
    ports:
    - name: port-3306
      port: 3306
      targetPort: 3306
    selector:
      app: playbook-etherpad
      service: mariadb
  register: output

- debug: var=output
  when: playbook_debug

- oso_service:
    service_name: etherpad
    project_name: playbook-etherpad
    labels:
      app: playbook-etherpad
      service: etherpad
    ports:
    - name: port-9001
      port: 9001
      targetPort: 9001
    selector:
      app: playbook-etherpad
      service: etherpad
  register: output

- debug: var=output
  when: playbook_debug

- oso_route:
    project_name: playbook-etherpad
    service_port: port-3306
    labels:
      app: playbook-etherpad
      service: mariadb
    route_name: mariadb-3306
    replace: true
    service_name: mariadb
    state: present
  register: output

- debug: var=output
  when: playbook_debug

- oso_route:
    project_name: playbook-etherpad
    service_port: port-9001
    labels:
      app: playbook-etherpad
      service: etherpad
    route_name: etherpad-9001
    replace: true
    service_name: etherpad
    state: present
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    project_name: playbook-etherpad
    labels:
      app: playbook-etherpad
      service: nginx
    deployment_name: nginx
    containers:
    - securityContext: {}
      name: nginx
      args:
      - nginx
      - -g
      - daemon off;
      image: fusordevel/playbook-etherpad-nginx
      ports:
      - 80
    replace: true
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    project_name: playbook-etherpad
    labels:
      app: playbook-etherpad
      service: mariadb
    deployment_name: mariadb
    containers:
    - securityContext: {}
      name: mariadb
      args:
      - mysqld
      image: fusordevel/playbook-etherpad-mariadb
      ports:
      - 3306
    replace: true
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    project_name: playbook-etherpad
    labels:
      app: playbook-etherpad
      service: etherpad
    deployment_name: etherpad
    containers:
    - securityContext: {}
      name: etherpad
      image: fusordevel/playbook-etherpad-etherpad
      args:
      - /opt/etherpad-lite/bin/run.sh
      ports:
      - 9001
    replace: true
  register: output

- debug: var=output
  when: playbook_debug
