version: "1"
services:
  etherpad:
    image: centos:7
    ports:
      - "80:8090"
    command: ['/usr/bin/systemctl', 'start', 'etherpad-lite', 'nginx']
    dev_overrides:
      environment:
        - "DEBUG=1"
 
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   
