
- kube_service:
    service_name: nginx
    ports:
    - name: port-80
      port: 80
      targetPort: 80
    selector:
      app: playbook-etherpad
      service: nginx
  register: output

- debug: var=output
  when: playbook_debug

- kube_service:
    service_name: mariadb
    ports:
    - name: port-3306
      port: 3306
      targetPort: 3306
    selector:
      app: playbook-etherpad
      service: mariadb
  register: output

- debug: var=output
  when: playbook_debug

- kube_service:
    service_name: etherpad
    ports:
    - name: port-9001
      port: 9001
      targetPort: 9001
    selector:
      app: playbook-etherpad
      service: etherpad
  register: output

- debug: var=output
  when: playbook_debug

- kube_deployment:
    labels:
      app: playbook-etherpad
      service: nginx
    deployment_name: nginx
    containers:
    - securityContext: {}
      name: nginx
      args:
      - nginx
      - -g
      - daemon off;
      image: playbook-etherpad-nginx:20170125153120
    replace: true
  register: output

- debug: var=output
  when: playbook_debug

- kube_deployment:
    labels:
      app: playbook-etherpad
      service: mariadb
    deployment_name: mariadb
    containers:
    - securityContext: {}
      name: mariadb
      args:
      - mysqld
      image: playbook-etherpad-mariadb:20170125153120
      ports:
      - 3306
    replace: true
  register: output

- debug: var=output
  when: playbook_debug

- kube_deployment:
    labels:
      app: playbook-etherpad
      service: etherpad
    deployment_name: etherpad
    containers:
    - securityContext: {}
      name: etherpad
      image: playbook-etherpad-etherpad:20170124161649
      args:
      - /opt/etherpad-lite/bin/run.sh
      ports:
      - 9001
    replace: true
  register: output

- debug: var=output
  when: playbook_debug
